name: torchsrc
channels:
  - defaults
dependencies:
  - tqdm
  - ninja
  - setuptools
  - numpy
  - pyyaml
  - scikit-learn
  - cffi
  - pandas
  - python=3.7
  - cmake
  - typing
  - nomkl
  - openblas

